version: '3.3'

services:

  alf-bot-redis:
    container_name: alf-bot-redis
    hostname: alf-bot-redis
    ports:
      - "6380:6379"
    image: redis:6.2.6
    networks:
      - home

  alf-bot-postges:
    container_name: alf-bot-postgres
    hostname: alf-bot-redis
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    image: postgres:15
    networks:
      - home

  alf-bot-fastapi:
    container_name: alf-bot-fastapi
    hostname: alf-bot-fastapi
    build:
      context: .
      dockerfile: ./src/app/Dockerfile
    ports:
      - "8000:8000"
      - "7000:7000"
    volumes:
      - ./src/app/logs/:/alfbot/src/app/logs/
    depends_on:
      - alf-bot-redis
      - alf-bot-postges
    networks:
      - home


  alf-bot-nginx:
    container_name: alf-bot-nginx
    hostname: alf-bot-nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - alf-bot-fastapi
    networks:
      - home



networks:
  home: {}
